const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
    const browser = await chromium.launch({ headless: true, channel: 'msedge' });
    const folder = path.resolve(__dirname, '../artifacts/library');
    fs.mkdirSync(folder, { recursive: true });
    const errors = [];
    const report = [];
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
        page.on('pageerror', error => errors.push(error.message));
        page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
        await page.goto('http://127.0.0.1:4173/library.html');
        await page.waitForFunction(() => window.libraryDiagnostics?.().ready, { timeout: 30000 });
        await page.waitForTimeout(1600);
        await page.screenshot({ path: path.join(folder, 'desktop.png') });
        report.push({ desktop: await page.evaluate(() => libraryDiagnostics()) });
        const spatial = await page.evaluate(() => libraryDiagnostics());
        assert.equal(spatial.polygonSides, 5, '通道应由五面书架围合');
        assert.ok(spatial.ribbons > 100, '慢速时也存在结构条带');
        assert.ok(spatial.vanishing.x > 0 && spatial.vanishing.y < 0, '通道朝画面右下方深入');
        assert.ok(spatial.pose.head.x > spatial.pose.feet.x && spatial.pose.head.y > spatial.pose.feet.y, 'C 姿态头部在右上，腿部在左下');
        assert.ok(spatial.pose.head.x - spatial.pose.feet.x > Math.abs(spatial.pose.head.y - spatial.pose.feet.y), '身体舒展侧漂，不呈直立下落');
        assert.equal(await page.evaluate(() => libraryDiagnostics().books), 56);
        await page.mouse.move(750, 600); await page.mouse.down();
        await page.waitForTimeout(1800);
        assert.ok(await page.evaluate(() => libraryDiagnostics().speed > 3.6), '长按应加速');
        const boosted = await page.evaluate(() => libraryDiagnostics());
        assert.ok(Math.abs(boosted.blurCenter.x - (boosted.vanishing.x + 1) / 2) < .001);
        assert.ok(Math.abs(boosted.blurCenter.y - (boosted.vanishing.y + 1) / 2) < .001);
        await page.screenshot({ path: path.join(folder, 'desktop-boost.png') });
        await page.mouse.up(); await page.waitForTimeout(1600);
        assert.ok(await page.evaluate(() => libraryDiagnostics().speed < 1.05), '松手应减速');
        await page.mouse.down(); await page.waitForTimeout(800);
        await page.evaluate(() => window.dispatchEvent(new Event('blur')));
        assert.equal(await page.evaluate(() => libraryDiagnostics().pressed), false);
        await page.mouse.up();
        await page.emulateMedia({ reducedMotion: 'reduce' });
        await page.waitForFunction(() => libraryDiagnostics().paused);
        const before = await page.evaluate(() => libraryDiagnostics().offset);
        await page.waitForTimeout(300);
        assert.equal(await page.evaluate(() => libraryDiagnostics().offset), before);
        await page.emulateMedia({ reducedMotion: 'no-preference' });
        await page.waitForFunction(() => !libraryDiagnostics().paused);
        await page.locator('#space').focus();
        await page.keyboard.down('Space');
        await page.waitForTimeout(32000);
        const loop = await page.evaluate(() => libraryDiagnostics());
        assert.ok(loop.speed > 3.9);
        const positions = [...loop.sections].sort((a, b) => a - b);
        for (let i = 1; i < positions.length; i++) assert.ok(Math.abs(positions[i] - positions[i - 1] - 9) < 0.00001, '完整循环后书架间隔不变');
        await page.keyboard.up('Space');
        await page.waitForTimeout(1400);
        assert.ok(await page.evaluate(() => libraryDiagnostics().speed < 1.05));
        assert.equal(await page.locator('#music-toggle').isEnabled(), true);
        assert.equal(await page.locator('iframe').count(), 0, '本地音轨不需要外部播放器');
        report.push({ fullLoop: 'PASS', keyboard: 'PASS', music: '本地配乐，独立音频测试验证播放' });
        const fps = await page.evaluate(() => new Promise(resolve => {
            const start = performance.now(); let frames = 0;
            function sample(now) { frames++; if (now - start >= 1500) resolve(Math.round(frames * 1000 / (now - start))); else requestAnimationFrame(sample); }
            requestAnimationFrame(sample);
        }));
        report.push({ desktopFps: fps });
        const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
        mobile.on('pageerror', error => errors.push(error.message));
        await mobile.goto('http://127.0.0.1:4173/library.html');
        await mobile.waitForFunction(() => window.libraryDiagnostics?.().ready);
        await mobile.waitForTimeout(1400);
        await mobile.screenshot({ path: path.join(folder, 'mobile.png') });
        assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        const mobileSpace = await mobile.evaluate(() => libraryDiagnostics());
        assert.ok(mobileSpace.vanishing.x > 0 && mobileSpace.vanishing.x < .8 && mobileSpace.vanishing.y < 0, '手机上消失点也在屏内右下方');
        const session = await mobile.context().newCDPSession(mobile);
        await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 195, y: 490 }] });
        await mobile.waitForTimeout(1600);
        assert.ok(await mobile.evaluate(() => libraryDiagnostics().speed > 3.5));
        await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
        await mobile.waitForTimeout(1600);
        assert.ok(await mobile.evaluate(() => libraryDiagnostics().speed < 1.05));
        report.push({ mobile: await mobile.evaluate(() => libraryDiagnostics()) });
        await mobile.setViewportSize({ width: 844, height: 390 });
        await mobile.waitForTimeout(300);
        await mobile.screenshot({ path: path.join(folder, 'mobile-landscape.png') });
        await page.emulateMedia({ reducedMotion: 'reduce' });
        await page.waitForFunction(() => libraryDiagnostics().paused);
        assert.equal(await page.evaluate(() => libraryDiagnostics().paused), true);
        assert.deepEqual(errors, []);
        report.push({ errors, result: 'PASS' });
        fs.writeFileSync(path.join(folder, 'checks.json'), JSON.stringify(report, null, 2));
        console.log(JSON.stringify(report, null, 2));
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
